### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by acossv**

### CODE REVIEW

**Comment by criscubillosedi** [comment]
Aceptado

**Review by jvaldesh — APPROVED** [review]
OK

**Review by clsepulvedaj — APPROVED** [review]
Review ok

**Review by criscubillos — APPROVED** [review]
ok

**Review by Zeranoob — APPROVED** [review]

**Review by juansalinasaedo — APPROVED** [review]
review ok

**Comment by Zeranoob** [comment]
Todo ok, excelente team

**Pull request merged**
